version: "2"

services:
  db:
    image: mysql
    env_file: .env
    volumes:
      - dbstore:/var/lib/mysql

  app:
    image: invoiceninja/invoiceninja
    #build: .
    depends_on: 
      - db
    env_file: .env
    volumes:
      - mediastore:/var/www/app/public/logo
    environment:
      APP_DEBUG: 1

  web:
    image: nginx
    depends_on: 
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    ports:
      - "80:80"

  cron:
    image: invoiceninja/invoiceninja
    user: www-data
    env_file: .env
    depends_on: 
      - app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        DB_USERNAME=root DB_PASSWORD=pwd /usr/local/bin/php /var/www/app/artisan ninja:send-invoices
        DB_USERNAME=root DB_PASSWORD=pwd /usr/local/bin/php /var/www/app/artisan ninja:send-reminders
        sleep 1d
      done
      EOF'

volumes:
  dbstore:
  mediastore:
