version: "2"

services:
  db:
    image: mysql
    env_file: .env
    volumes:
      - dbstore:/var/lib/mysql

  app:
    image: invoiceninja/invoiceninja
    #build: .
    depends_on: 
      - db
    env_file: .env
    volumes:
      - mediastore:/var/www/app/public/logo
    environment:
      APP_DEBUG: 1

  web:
    image: nginx
    depends_on: 
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    ports:
      - "80:80"

volumes:
  dbstore:
  mediastore:
